PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX CL: <http://purl.obolibrary.org/obo/CL_>

SELECT (COUNT (DISTINCT ?term) as ?pclcells)
WHERE {
  	?term a owl:Class . 
  	?term rdfs:subClassOf* CL:0000003
  FILTER(isIRI(?term) && (STRSTARTS(str(?term), "http://purl.obolibrary.org/obo/PCL_")))
}