PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?class
WHERE {
  ?class a owl:Class .
  FILTER (
    STRSTARTS(STR(?class), "http://identifiers.org/ensembl/") ||
    STRSTARTS(STR(?class), "http://identifiers.org/ncbigene/")
  )
}