name: Validate Dendrograms

# Since this validation fails, added as a separate action and disabled. I future can be integrated to main build task.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - 'src/dendrograms/**.json'
      - '.github/workflows/dendrogram_check.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-dendrograms:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: validate dendrograms
        run: python ./src/scripts/dendrogram_validator.py
